[tool.poetry]
name = "answer-service"
version = "0.1.0"
description = ""
authors = ["minhnq0702 <minhnq.0702@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
